server:
  port: 9061

spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_management?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: dbsrbs3172!

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

